######################################################################
# Automatically generated by qmake (3.0) ?? ???. 16 20:40:55 2013
######################################################################

TEMPLATE = app
TARGET = CurrentProject
INCLUDEPATH += .

# Input
SOURCES += application.cpp
CONFIG += qt warn_on release_and_debug
QT += widgets
